#ddev-generated
COPY install_sqlsrv.sh /tmp/

RUN apt-get update && DEBIAN_FRONTEND=noninteractive sudo apt-get install -y -o Dpkg::Options::="--force-confold" --no-install-recommends --no-install-suggests gcc make autoconf libc-dev pkg-config php-pear
RUN sudo /bin/bash /tmp/install_sqlsrv.sh
